apiVersion: apps/v1
kind: Deployment
metadata:
  name: vehicle-test
  namespace: jetson
  labels:
    app: jetson
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jetson
  template:
    metadata:
      labels:
        app: jetson
    spec:
      nodeName: edge.xavier
      hostNetwork: true
      containers:
      - name: vehicle-test
        image: pdsl-registry.cn-shenzhen.cr.aliyuncs.com/jetson/deepstream-l4t:vehicle-v1.0
        imagePullPolicy: IfNotPresent
        env:
          - name: "rows"
            value: "2"
          - name: "columns"
            value: "2"
          - name: "sources"
            value: "4"
          - name: "rtsp_urls"
            value: "rtsp://admin:12345678a@192.168.1.102:554/h264/ch1/main/av_stream,
                    rtsp://admin:12345678a@192.168.1.102:554/h264/ch1/main/av_stream,
                    rtsp://admin:12345678a@192.168.1.102:554/h264/ch1/main/av_stream,
                    rtsp://admin:12345678a@192.168.1.102:554/h264/ch1/main/av_stream"
        volumeMounts:
          - name: tmp
            mountPath: /tmp/
      volumes:
        - name: tmp
          hostPath:
            path: /tmp/
            type: DirectoryOrCreate
