apiVersion: apps/v1
kind: Deployment
metadata:
  name: vehicle-test
  namespace: jetson
  labels:
    app: jetson
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jetson
  template:
    metadata:
      labels:
        app: jetson
    spec:
      nodeName: edge.xavier
      hostNetwork: true
      containers:
      - name: vehicle-test
        image: pdsl-registry.cn-shenzhen.cr.aliyuncs.com/jetson/deepstream-l4t:vehicle-v1.3
        imagePullPolicy: IfNotPresent
        env:
          - name: "DISPLAY"
            value: ":1"
          - name: "bitrate"
            value: "1000000"
          - name: "rows"
            value: "2"
          - name: "columns"
            value: "2"
          - name: "sources"
            value: "3"
          - name: "rtsp_ids"
            value: "rtsp0, rtsp1, rtsp2"
          - name: "rtsp_urls"
            value: "rtsp://admin:12345678a@192.168.1.164:554/h264/ch1/main/av_stream,
                    rtsp://admin:12345678a@192.168.1.167:554/h264/ch1/main/av_stream,
                    rtsp://admin:12345678a@192.168.1.168:554/h264/ch1/main/av_stream"
          - name: "host"
            value: "kafka"
          - name: "port"
            value: "9092"
          - name: "topic"
            value: "test"
        volumeMounts:
          - name: tmp
            mountPath: /tmp/
      volumes:
        - name: tmp
          hostPath:
            path: /tmp/
            type: DirectoryOrCreate
